Cass402/Fluxa

docs/projectOverview_and_executiveSummary.md

Project Overview and Executive Summary

---

docs/architecture.md

Architecture Overview

---

docs/detailedTechnicalDesign.md

Detailed Technical Design

---

docs/threatModel_and_riskAssessment.md

Threat Model & Risk Assessment

---

docs/securityTestingChecklist.md

Security Testing Checklist

---

docs/testPlan_coverageReport.md

Test Plan + Coverage Report

---

docs/userJourney.md

UX Flow / User Journey

---

docs/tokenomics_and_protocolFee.md

Tokenomics & Protocol Fee Design

---

docs/businessModel_and_monetizationPlan.md

Business Model & Monetization Plan

---

Dockerfile

Dockerfile creation

---

docker-entry_point.sh

Docker Entrypoint Script

---

.dockerignore

Set up the project structure

---

scripts/deploy.sh

Setup deploy script

---

scripts/setup-test-accounts.sh

Setup test-accounts script

---

.gitignore
Fluxa_Docker_Setup.md
Makefile
README.md

Docker-Setup Guide

---

.githooks/pre-commit
.github/dependabot.yml
.github/workflows/ci-cd.yml
.github/workflows/release.yml
Dockerfile
Makefile
README.md
docker-compose.yml
docs/development_environment.md
frontend/package-lock.json
frontend/package.json

Setup git precommit hooks

---

.gitignore
Anchor.toml
Cargo.lock
Cargo.toml
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/page.tsx
frontend/src/components/charts/PriceChart.tsx
frontend/src/components/ui/input.tsx
frontend/src/styles/tokens.ts
programs/src/amm_core/Cargo.toml
programs/src/amm_core/constants.rs
programs/src/amm_core/errors.rs
programs/src/amm_core/instructions/collect_fees.rs
programs/src/amm_core/instructions/create_position.rs
programs/src/amm_core/instructions/create_token_pair.rs
programs/src/amm_core/instructions/initialize_pool.rs
programs/src/amm_core/instructions/mod.rs
programs/src/amm_core/instructions/modify_position.rs
programs/src/amm_core/instructions/swap.rs
programs/src/amm_core/lib.rs
programs/src/amm_core/math.rs
programs/src/amm_core/token_pair.rs
programs/src/impermanent_loss/Cargo.toml
programs/src/impermanent_loss/lib.rs
programs/src/order_book/Cargo.toml
programs/src/order_book/lib.rs
programs/src/yield_optimization/Cargo.toml
programs/src/yield_optimization/lib.rs
tests/unit/token-pair.test.ts

Token Pair Account Structure

---

frontend/next-env.d.ts
frontend/package-lock.json
frontend/package.json
frontend/tsconfig.json
package-lock.json
package.json
programs/src/amm_core/errors.rs
programs/src/amm_core/instructions/initialize_pool.rs
programs/src/amm_core/math.rs
scripts/initialize-pool.ts
tests/unit/initialize-pool.test.ts
tests/unit/token-pair.test.ts
types/bn.js.d.ts

Liquidity Pool Creation

---

programs/src/amm_core/instructions/swap.rs

Basic Swap Functionality

---

programs/src/amm_core/errors.rs
programs/src/amm_core/instructions/collect_fees.rs
programs/src/amm_core/pool_state.rs

Fee Accrual Mechanism

---

programs/src/amm_core/lib.rs
programs/src/amm_core/position_manager.rs
programs/src/amm_core/utils/mod.rs

Position Management

---

programs/src/amm_core/errors.rs
programs/src/amm_core/instructions/swap.rs
programs/src/amm_core/math.rs
programs/src/amm_core/pool_state.rs
programs/src/amm_core/position_manager.rs
programs/src/impermanent_loss/instructions/check_rebalance_condition.rs
programs/src/impermanent_loss/instructions/initialize_il_mitigation.rs
programs/src/impermanent_loss/lib.rs

Virtual Reserves Calculation
